# Generated by Django 4.0.5 on 2022-07-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
