# Generated by Django 4.0.5 on 2022-07-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_projectphoto_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='image',
            field=models.FileField(upload_to='attachments'),
        ),
    ]
