# Generated by Django 4.0.5 on 2022-07-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_project_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='project_id',
            new_name='project',
        ),
    ]
